git mv DownloadUpdateDialog.ar.resx Resources\DownloadUpdateDialog.ar.resx
git mv DownloadUpdateDialog.da.resx Resources\DownloadUpdateDialog.da.resx
git mv DownloadUpdateDialog.de.resx Resources\DownloadUpdateDialog.de.resx
git mv DownloadUpdateDialog.es.resx Resources\DownloadUpdateDialog.es.resx
git mv DownloadUpdateDialog.fr.resx Resources\DownloadUpdateDialog.fr.resx
git mv DownloadUpdateDialog.it.resx Resources\DownloadUpdateDialog.it.resx
git mv DownloadUpdateDialog.ja-JP.resx Resources\DownloadUpdateDialog.ja-JP.resx
git mv DownloadUpdateDialog.ko.resx Resources\DownloadUpdateDialog.ko.resx
git mv DownloadUpdateDialog.nl.resx Resources\DownloadUpdateDialog.nl.resx
git mv DownloadUpdateDialog.pl.resx Resources\DownloadUpdateDialog.pl.resx
git mv DownloadUpdateDialog.pt-BR.resx Resources\DownloadUpdateDialog.pt-BR.resx
git mv DownloadUpdateDialog.pt.resx Resources\DownloadUpdateDialog.pt.resx
git mv DownloadUpdateDialog.resx Resources\DownloadUpdateDialog.resx
git mv DownloadUpdateDialog.ru.resx Resources\DownloadUpdateDialog.ru.resx
git mv DownloadUpdateDialog.sk.resx Resources\DownloadUpdateDialog.sk.resx
git mv DownloadUpdateDialog.sv.resx Resources\DownloadUpdateDialog.sv.resx
git mv DownloadUpdateDialog.th.resx Resources\DownloadUpdateDialog.th.resx
git mv DownloadUpdateDialog.tr.resx Resources\DownloadUpdateDialog.tr.resx
git mv DownloadUpdateDialog.zh-tw.resx Resources\DownloadUpdateDialog.zh-tw.resx
git mv DownloadUpdateDialog.zh.resx Resources\DownloadUpdateDialog.zh.resx
git mv RemindLaterForm.ar.resx Resources\RemindLaterForm.ar.resx
git mv RemindLaterForm.da.resx Resources\RemindLaterForm.da.resx
git mv RemindLaterForm.de.resx Resources\RemindLaterForm.de.resx
git mv RemindLaterForm.es.resx Resources\RemindLaterForm.es.resx
git mv RemindLaterForm.fr.resx Resources\RemindLaterForm.fr.resx
git mv RemindLaterForm.it.resx Resources\RemindLaterForm.it.resx
git mv RemindLaterForm.ja-JP.resx Resources\RemindLaterForm.ja-JP.resx
git mv RemindLaterForm.ko.resx Resources\RemindLaterForm.ko.resx
git mv RemindLaterForm.nl.resx Resources\RemindLaterForm.nl.resx
git mv RemindLaterForm.pl.resx Resources\RemindLaterForm.pl.resx
git mv RemindLaterForm.pt-BR.resx Resources\RemindLaterForm.pt-BR.resx
git mv RemindLaterForm.pt.resx Resources\RemindLaterForm.pt.resx
git mv RemindLaterForm.resx Resources\RemindLaterForm.resx
git mv RemindLaterForm.ru.resx Resources\RemindLaterForm.ru.resx
git mv RemindLaterForm.sk.resx Resources\RemindLaterForm.sk.resx
git mv RemindLaterForm.sv.resx Resources\RemindLaterForm.sv.resx
git mv RemindLaterForm.th.resx Resources\RemindLaterForm.th.resx
git mv RemindLaterForm.tr.resx Resources\RemindLaterForm.tr.resx
git mv RemindLaterForm.zh-tw.resx Resources\RemindLaterForm.zh-tw.resx
git mv RemindLaterForm.zh.resx Resources\RemindLaterForm.zh.resx
git mv UpdateForm.ar.resx Resources\UpdateForm.ar.resx
git mv UpdateForm.da.resx Resources\UpdateForm.da.resx
git mv UpdateForm.de.resx Resources\UpdateForm.de.resx
git mv UpdateForm.es.resx Resources\UpdateForm.es.resx
git mv UpdateForm.fr.resx Resources\UpdateForm.fr.resx
git mv UpdateForm.it.resx Resources\UpdateForm.it.resx
git mv UpdateForm.ja-JP.resx Resources\UpdateForm.ja-JP.resx
git mv UpdateForm.ko.resx Resources\UpdateForm.ko.resx
git mv UpdateForm.nl.resx Resources\UpdateForm.nl.resx
git mv UpdateForm.pl.resx Resources\UpdateForm.pl.resx
git mv UpdateForm.pt-BR.resx Resources\UpdateForm.pt-BR.resx
git mv UpdateForm.pt.resx Resources\UpdateForm.pt.resx
git mv UpdateForm.resx Resources\UpdateForm.resx
git mv UpdateForm.ru.resx Resources\UpdateForm.ru.resx
git mv UpdateForm.sk.resx Resources\UpdateForm.sk.resx
git mv UpdateForm.sv.resx Resources\UpdateForm.sv.resx
git mv UpdateForm.th.resx Resources\UpdateForm.th.resx
git mv UpdateForm.tr.resx Resources\UpdateForm.tr.resx
git mv UpdateForm.zh-tw.resx Resources\UpdateForm.zh-tw.resx
git mv UpdateForm.zh.res Resources\UpdateForm.zh.res